### PR TITLE
Rework location of AddCardComponent

### PR DESCRIPTION
**Pull request by ahmedhamodi**
Tackles two points:
- passing in functions from main component to the AddCardComponent
- render in AddCardComponent on CreateEditForm.js component

### CODE REVIEW

**Review by GodGreg — APPROVED** [review]
Lgtm. Will probably have to be rebased

**Comment by ahmedhamodi** [comment]
> Lgtm. Will probably have to be rebased

Agreed. Let's get the other PRs merged first and I can rework this one to work with those after.

**Comment by ahmedhamodi** [comment]
Will resolve conflicts at next meeting.

**Comment by ahmedhamodi** [comment]
@GodGreg want to re-review?

**Pull request merged**
