### PR TITLE
Greg/formcreationcssforreal

### PR DESCRIPTION
**Pull request by GodGreg**
Ahmed i am sorry for the very large pull request

This is a squash of 3 PRs

- moved createForm to createEditForm

-changed formID to be programID in formSchema and updated everywhere else accordingly

- Updated CSS for Sections Card
- Updated CSS for Questions Card
- The first section is an identity question that can't be deleted.
- Active and non-active sections have separate CSS
- All components in the Sections Card updated WITHOUT LAGGG (We had it so every character re-rendered the entire form) I fixed paintfully ugggg (This is the bulk of the changes)
- Tested scrolling and made some fixes. 
- General code cleanup

TODO: Replicate the same logic for the question cards for saving and active/non-active (separate PR)

### CODE REVIEW

**Comment by GodGreg** [comment]
will fix lint errors if ur online at 4:03am plz wait

**Comment by GodGreg** [comment]
TODO: react doesn't like my useEffect using things not in the dependency array. But putting things in the dependency array causes infinite renders. 

So I will have to wrap both initiateForm and SaveForm in a useCallback()

**Comment by ahmedhamodi** [comment]
Thankfully I went to sleep just before 4 😆 . I'll review after travis CI passes :)

**Review by ahmedhamodi — APPROVED** [review]
Looked through code and ran locally, it all looks good. A few comments though.
- the create form button is removed but not added to the dropdown
- there is a ton of text overflowing (see image 1 below)
- the dropdown menu on the cards is not working atm (see image 2 below)
- clicking the 3 dots on the first section opens the menu in a weird spot (see image 3)

Image 1:
image

Image 2:
image

Image 3:
image

These can be addressed and fixed in a later PR!

**Comment by GodGreg** [comment]
@ahmedhamodi I am aware of most of these problems already, but I agree we can merge this in and have a separate PR for css fixes. 

Going to work on the questions update next now that sections are done.

**Pull request merged**
