### PR TITLE
added submission screen

### PR DESCRIPTION
**Pull request by Tayef-Shah**

### CODE REVIEW

**Review by ahmedhamodi — COMMENTED** [review]
There appears to be additional text showing up on the screen with the "submit" button.

See design below:
image

Code looks good. If you get this change in, I can approve.

**Comment by ahmedhamodi** [comment]
Also, doesn't look like the routing is changing when going to the final submission page. Based on our discussion, this was the intention. Is there a reason it isn't included here?

**Comment by Tayef-Shah** [comment]
Yeah, I originally had the routing going, but I changed it last minute for the following reason:

The data for the confirmation page (header photo and program name) is based on programId which comes from the user auth context. The auth context is not present for users submitting forms since they don't need to log in. So in order to have that data, I kept the submission screen styling in the same component. I could pass the formId in the URL, but in the past the group has had some discussions around the robustness of only carrying around the formID by URL.

**Comment by Tayef-Shah** [comment]
This is what the UI looks like as of now
Screen Shot 2020-12-08 at 6 38 14 PM

**Review by GodGreg — APPROVED** [review]
LGTM. 

Saw a demo on Monday and works fine

**Review by ahmedhamodi — APPROVED** [review]
Assuming we are okay with the routing situation, this lgtm too!

**Pull request merged**
