### PR TITLE
Feedback Form Card

### PR DESCRIPTION
**Pull request by hyunzeekim**
Feedback form card

### CODE REVIEW

**Review by GodGreg — APPROVED** [review]
I just need to edit some css. Otherwise, it looks good!

**Comment by GodGreg** [comment]
@brittanylau @hyunzeekim 

I changed the popover to be a dialog. In both cases, the user was unable to close it by clicking outside. Popovers are pretty annoying in general since it shares quite a few css classes with other material components. 

Let me know if you are both okay with this from a design/dev standpoint respectively. (We can change the location of the icon haha)

image

**Comment by brittanylau** [comment]
Looks good to me! 👍

**Comment by GodGreg** [comment]
@hyunzeekim Feel free to merge when you are ready

**Pull request merged**
